# Ansible playbook
- name: Set up the containers
  hosts: stasmo.wtf
  vars:
    app_port: 80
    mongo_db: bittrextoolsdb
    mongo_user: stasmo
    mongo_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38633866386333383035363731343362336662643233323138383735383136313761373131396330
          3036656132356539373238316637663532613266663936640a306265613336316363616634613339
          64643339396531393632313731323837373736356166303636346535393939636166306231653230
          3761636434366632310a613463363236336465323130666636393236393433636637363138333664
          3736
    certbot_install_from_source: yes
  roles:
    - role: geerlingguy.certbot
      become: yes
  tasks:
    - docker_container:
        name: server
        state: absent
    - shell: letsencrypt certonly --agree-tos --email simon@staszkiewicz.ca --noninteractive --standalone -d stasmo.wtf
      become: yes
    - docker_container:
        restart_policy: always
        image: mongo
        name: bittrex_mongo
        volumes:
          - "{{ ansible_user_dir}}/mongodata:/data/db"
    - docker_container:
        restart_policy: always
        image: stasmo/bittrex-tools
        name: server
        volumes:
          - /etc/letsencrypt:/certs
        ports:
          - "80:80"
          - "443:443"
        env:
          DATABASE_STRING: 'mongodb://bittrex_mongo/bittrex_tools'
          PORT: "{{ app_port }}"
          SSL: 'true'
          CERTS_DIR: /certs/live/stasmo.wtf
        command: npm start